language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

php:
  - 7.3
  - 7.4
  - 8.0

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer install $COMPOSER_ARGS
  - stty cols 120 && composer show

script:
  - composer cs-check

notifications:
  email: false
